---
# Ansible Playbook to upgrade Cisco IOS


- name: Upgrade Cisco IOS
  hosts: ios_upgrade_asr920
  connection: network_cli
  vars_files:
    - ios_upgrade_vars.yml
  tasks:
    - name: Checking current {{ ansible_net_iostype }} version
      cisco.ios.ios_facts:

    - name: Device hardware model validation
      ansible.builtin.assert:
        that:
          - ansible_net_model in device_models
        fail_msg: Device hardware model NOT valid. Upgrade would be SKIPPED for this host

    - name: Verifying if current version is equal to upgrade version
      ansible.builtin.assert:
        that:
          - ansible_net_version != upgrade_ios_version
        success_msg: "Current IOS-XE version IS NOT up to date. Upgrade WILL proceed for this device"
        fail_msg: "Current IOS-XE version IS up to date. Upgrade WILL BE SKIPPED for this device"